#!/bin/bash

set -e

VERSION=$(cat debian/control | grep Standards-Version | cut -d' ' -f2)
OUTPUT=$(kubescape version)
echo ${OUTPUT}
if [ "${OUTPUT}" != "Your current version is: v${VERSION} [git enabled in build: true]" ]; then
    exit 1;
fi
